name: Make Check

on:
  push:
    branches:
          - master
          - xmlsec-1_2_x
  pull_request:
    branches:
          - master
          - xmlsec-1_2_x
  workflow_dispatch:

jobs:
  check-ubuntu-openssl300:
    runs-on: ubuntu-20.04
    steps:
    - name: install dependencies
      run: |
          sudo apt update
          sudo apt install automake autoconf libtool libtool-bin libltdl-dev libltdl7
          sudo apt install libxml2 libxml2-dev libxslt1.1 libxslt1-dev
          sudo apt install libssl1.1 libssl-dev libnspr4 libnspr4-dev libnss3 libnss3-dev libnss3-tools libgcrypt20 libgcrypt20-dev libgnutls28-dev
    - uses: actions/checkout@v2
    - name: create-build-dirs
      run: |
          mkdir build.dir install.dir
    - name: configure
      working-directory: build.dir
      run: |
          ../autogen.sh --prefix=${GITHUB_WORKSPACE}/install.dir
    - name: make
      working-directory: build.dir
      run: |
          make
    - name: make check
      working-directory: build.dir
      run: |
          make check
    - name: make install
      working-directory: build.dir
      run: |
          make install